### PR TITLE
fixes #21 - cannot read property autoHideDropdown of undefined

### LINKED ISSUE #21: Cannot read property `autoHideDropdown` of undefined
When using this in a tabbed form, if going away from and back to a tab containing an angular-auto-complete instance, the above error pops up. 

    TypeError: Cannot read property 'autoHideDropdown' of undefined
        at i.autoHide (dll.vendor.js:1)
        at dll.vendor.js:1
        at Object.b [as forEach] (dll.vendor.js:1)
        at Object.hideAllInactive (dll.vendor.js:1)
        at a (dll.vendor.js:1)
        at dll.vendor.js:1
        at c.$eval (dll.vendor.js:1)
        at c.$digest (dll.vendor.js:1)
        at c.$apply (dll.vendor.js:1)
        at dll.vendor.js:1

Ideally, the lib should provide a hook to delete any and all listeners placed on window object to allow removing them.

I pushed a quickfix on a fork and I'll make a pull-request. 

I simply replaced:

    if (that.options.autoHideDropdown) {
      ...

with

    if (that.options && that.options.autoHideDropdown) {
      ...

### PR DESCRIPTION
**Pull request by andrei-gheorghiu**
fix for https://github.com/vickramravichandran/angular-auto-complete/issues/21

### CODE REVIEW

**Comment by vickramravichandran** [comment]
Why is it failing only there? The properties of `that.options` are read in many other places. For instance:
`getSelectedCssClass()` reads `that.options.selectedCssClass`
`_query()` reads `that.options.pageSize` & `that.options.pagingEnabled`

...and so on...

**Comment by andrei-gheorghiu** [comment]
I think the lib is placing a listener on the window object which checks the options to see if it should run the autoHide or not. But the instance has been destroyed. I'm not an expert on routing and how tabbed views work in angular and what happens there at DOM level, but the error is real. 

If I must, I'll try to create a fiddle with the error. But I don't see any downside to this fix. Is there any?

**Comment by vickramravichandran** [comment]
If `that.options` might be undefined then I would like to apply the fix throughout the plugin. Here is what I have in mind...

Create a object hash of valid options from `defaultOptions`

```javascript
var OPTIONS = {};
_.each(_.keys(defaultOptions), function(key) { 
    OPTIONS[key] = key;
});

/*
The result of the code above will be...
var OPTIONS = {
    selectedCssClass: 'selectedCssClass',
    autoHideDropdown: 'autoHideDropdown',
    ...
    ...
}
*/
```

Now I can create a helper method to get an option value instead of accessing it directly...

```javascript
function _getOption(option, defaultValue) {
    if (OPTIONS.hasOwnProperty(option) && that.options && that.options.hasOwnProperty(option)) {
	    return that.options[option];
    }

    return defaultValue;
}
```

Now I can replace all instances of "options.property" with

```javascript
_getOption(OPTIONS.autoHideDropdown);
_getOption(OPTIONS.selectedCssClass);
```

**Comment by vickramravichandran** [comment]
I cherry picked your commit and merged to master. I have published version 1.7.3 to npm.

**Pull request closed without merging**
